# Generated by Django 5.0.6 on 2026-02-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
