# Generated by Django to create encryption key model

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_create_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('key_type', models.CharField(choices=[('fernet', 'Fernet'), ('aes', 'AES')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'encryption key',
                'verbose_name_plural': 'encryption keys',
                'ordering': ['-created_at'],
            },
        ),
    ]