# Generated by Django 5.0.6 on 2026-02-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_create_encryption_key'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
